### ISSUE TITLE
关于合约交易出错等相关问题求教。

### ISSUE THREAD

**Issue by Cpyyyy** [alpha-baby/fvoting#1]
**您好，抱歉，再次打扰您 我是那位给您发邮件的小白。**
今天调试能够成功进入您写的网页，也成功的与matemask建立了连接。
但是在进行投票项目的创建以及权重购买时发生了错误。

- 一是无法进行投票项目的创建，点击按钮，网页无响应。（如下）

![无法创建](https://user-images.githubusercontent.com/81951209/113673772-f9f50f00-96eb-11eb-9f3b-a0966355f2aa.png)

- 二是无法进行权重的购买，会报错。（如下）
![ 交易出错](https://user-images.githubusercontent.com/81951209/113673980-39bbf680-96ec-11eb-8094-772ad9285743.png)

不知是否是因为没有按照您文档里说的“需要智能合约的ABI和部署地址”，应该如何操作呢？
向您求教，期待您的答复，谢谢。

**Comment by alpha-baby** [comment]
关于咋开发这种东西，请自己学习，我无法为你解答。因为我又不是一直干这个，我自己的忘记了。

**Comment by Cpyyyy** [comment]
> 关于咋开发这种东西，请自己学习，我无法为你解答。因为我又不是一直干这个，我自己的忘记了。

好的好的 麻烦您了 谢谢您 祝生活愉快。
